### ISSUE TITLE
If user not logged in, show Login buttons

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-theme_wwu2019#14] opened 2020-03-04 14:24 UTC

**Comment by NinaHerrmann** [comment] 2020-03-04 16:06
duplicate of #6 ?

**Comment by Dagefoerde** [comment] 2020-03-05 08:04
No. The page has to be implemented (#6) AND the links to that page are missing from the navigation (this issue)

**Closed** 2020-03-05 12:35 UTC
